theme: jekyll-theme-midnight
title: nkREPAIR
description: A website containing guides for hardware repairs, configuring Windows and GNU/Linux systems, and other IT related projects

layout: page
title: "About"
permalink: /about/
