theme: jekyll-theme-midnight
title: nkREPAIR
description: A website containing guides and scripts for configuring Windows and GNU/Linux systemsdescription: A website containing guides for hardware repairs, configuring Windows and GNU/Linux systems, and other IT related projects
